name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Run Tests
        env:
          SURREALDB_URL: ${{ secrets.SURREALDB_URL }}
          SURREALDB_NAMESPACE: ${{ secrets.SURREALDB_NAMESPACE }}
          SURREALDB_DATABASE: ${{ secrets.SURREALDB_DATABASE }}
          GITHUB_ACTIONS: ${{ secrets.GITHUB_ACTIONS }}
        run: go test ./...
